CREATE DATABASE IF NOT EXISTS QLBanSach;

USE QLBanSach;

CREATE TABLE
  IF NOT EXISTS ChuDe (
    MaChuDe INT PRIMARY AUTO_INCREMENT COMMENT (""),
    TenChuDe VARCHAR(225) COMMENT ("")
  );

CREATE TABLE
  IF NOT EXISTS NhaXuatBan (
    MaNXB PRIMARY AUTO_INCREMENT COMMENT (""),
    TenNXB VARCHAR(225) NOT NULL UNIQUE COMMENT (""),
    DiaChi VARCHAR(225) COMMENT (""),
    DienThoai VARCHAR(11) UNIQUE NOT NULL COMMENT (""),
  );

CREATE TABLE
  IF NOT EXISTS TacGia (
    MaTacGia INT PRIMARY KEY AUTO_INCREMENT COMMENT (""),
    TenTacGia VARCHAR(225) NOT NULL COMMENT (""),
    DiaChi VARCHAR(225) COMMENT (""),
    TieuSu VARCHAR(225) COMMENT (""),
    DienThoai VARCHAR(11) UNIQUE NOT NULL COMMENT (""),
  );

CREATE TABLE
  IF NOT EXISTS KhachHang (
    MaKH INT PRIMARY AUTO_INCREMENT COMMENT ("Mã khách hàng"),
    TaiKhoan VARCHAR(125) UNIQUE NOT NULL,
    MathKhau VARCHAR(125) UNIQUE NOT NULL,
    Email VARCHAR(125) UNIQUE NOT NULL,
    HoTen VARCHAR(225) NOT NULL,
    DienThoai VARCHAR(11) UNIQUE NOT NULL,
    DiaChi VARCHAR(225),
    GioiTinh VARCHAR(10),
    NgaySinh DAtetime,
  );

CREATE TABLE
  IF NOT EXISTS DonHang (
    MaDonHang INT PRIMARY KEY AUTO_INCREMENT,
    DaThanhToan BOOLEAN DEFAULT FALSE,
    TinhTrangGH VARCHAR(100) DEFAULT "Đang chuẩn bị",
    NgayGiao DAtetime NOT NULL,
    NgayDat DAtetime DEFAULT CURRENT_TIMESTAMP,
    MaKhachHang INT NOT NULL,
    FOREIGN KEY (MaKhachHang) REFERENCE KhachHang (MaKhachHang),
  );

CREATE TABLE
  IF NOT EXISTS Sach (
    MaSach INT PRIMARY KEY AUTO_INCREMENT COMMENT (""),
    TenSach VARCHAR(225) NOT NULL UNIQUE COMMENT (""),
    GiaBan DECIMAL(10 COMMENT (""), 2) NOT NULL COMMENT (""),
    MoTa VARCHAR(225) COMMENT (""),
    SoLUongTon DECIMAL() NOT NULL DEFAULT 0 COMMENT (""),
    AnhBia VARCHAR(225) COMMENT (""),
    NgayCapNhat DATETIME DEFAULT UPDATE_TIMESTAMP COMMENT (""),
    -- Foreign keys
    MaChuDe INT NOT NULL COMMENT (""),
    MaNXB INT NOT NULL COMMENT (""),
    -- Constraint
    CONSTRAINT FK_Sach_ChuDe FOREIGN KEY (MaChuDe) REFERENCE ChuDe (MaChuDe),
    CONSTRAINT FK_Sach_NhaXB FOREIGN KEY (MaNXB) REFERENCE NhaXuatBan (MaNXB),
  );

CREATE TABLE
  IF NOT EXISTS TacGia_Sach (
    Ma INT PRIMARY KEY AUTO_INCREMENT COMMENT (""),
    VaiTro VARCHAR(100) NOT NULL COMMENT (""),
    ViTri VARCHAR(100) NOT NULL COMMENT (""),
    -- Foreign keys
    MaTacGia INT NOT NULL COMMENT (""),
    MaSach INT NOT NULL COMMENT (""),
    -- Constraint
    CONSTRAINT FK_TGS_TacGia FOREIGN KEY (MaTacGia) REFERENCE TacGia (MaTacGia),
    CONSTRAINT FK_TGS_Sach FOREIGN KEY (MaSach) REFERENCE Sach (MaSach),
  );

CREATE TABLE
  IF NOT EXISTS DonHang_Sach (
    MaDHSach INT PRIMARY KEY AUTO_INCREMENT COMMENT (""),
    SoLuong DECIMAL(3, 10) NOT NULL DEFAULT 1 COMMENT (""),
    DonGia DOUBLE NOT NULL COMMENT (""),
    -- Foreign keys
    MaDonHang INT NOT NULL COMMENT (""),
    MaSach INT NOT NULL COMMENT (""),
    -- Constraint
    CONSTRAINT FK_DHS_DonHang FOREIGN KEY (MaDonHang) REFERENCE DonHang (MaDonHang),
    CONSTRAINT FK_DHS_Sach FOREIGN KEY (MaSach) REFERENCE Sach (MaSach),
  );
